Console.ForegroundColor =ConsoleColor.DarkYellow;
Console.WriteLine("November Rain - Guns N' Rsoses");
Console.ResetColor();
Console.WriteLine("\nWhen I look into your eyes");
Console.WriteLine("I can see a love restrained");
Console.WriteLine("But darlin' when I hold you");
Console.WriteLine("Don't you know I feel the same?\n");
Console.ForegroundColor =ConsoleColor.Red;
Console.WriteLine("\nNothin' lasts forever");
Console.WriteLine("And we both know hearts can change");
Console.WriteLine("And it's hard to hold a candle");
Console.WriteLine("In the cold November rain\n");
Console.ResetColor();
Console.WriteLine("\nWe've been through this such a long long time");
Console.WriteLine("Just tryin' to kill the pain, ooh yeah");
Console.WriteLine("Love is always coming, love is always going");
Console.WriteLine("No one's really sure who's lettin' go today");
Console.WriteLine("Walking away\n");
Console.WriteLine("\nIf we could take the time to lay it on the line");
Console.WriteLine("I could rest my head just knowin' that you were mine");
Console.WriteLine("All mine");
Console.WriteLine("So if you want to love me then darlin' don't refrain");
Console.WriteLine("Or I'll just end up walkin' in the cold November rain\n");
Console.WriteLine("\nDo you need some time on your own?");
Console.WriteLine("Do you need some time all alone?");
Console.WriteLine("Ooh, everybody needs some time on their own");
Console.WriteLine("Ooh, don't you know you need some time all alone\n");
Console.WriteLine("\nI know it's hard to keep an open heart");
Console.WriteLine("When even friends seem out to harm you");
Console.WriteLine("But if you could heal a broken heart");
Console.WriteLine("Wouldn't time be out to charm you?");
Console.WriteLine("Oh, oh, oh\n");
Console.WriteLine("\nSometimes I need some time on my own");
Console.WriteLine("Sometimes I need some time all alone");
Console.WriteLine("Ooh, everybody needs some time on their own");
Console.WriteLine("Ooh, don't you know you need some time all alone\n");
Console.WriteLine("\nAnd when your fears subside");
Console.WriteLine("And shadows still remain, oh yeah");
Console.WriteLine("I know that you can love me when there's no one left to blame");
Console.WriteLine("So never mind the darkness, we still can find a way");
Console.WriteLine("'Cause nothin' lasts forever, even cold November rain\n");
Console.WriteLine("\nDon't ya think that you need somebody?");
Console.WriteLine("Don't ya think that you need someone?");
Console.WriteLine("Everybody needs somebody");
Console.WriteLine("You're not the only one");
Console.WriteLine("You're not the only one\n");
Console.WriteLine("\nDon't ya think that you need somebody?");
Console.WriteLine("Don't ya think that you need someone?");
Console.WriteLine("Everybody needs somebody");
Console.WriteLine("You're not the only one");
Console.WriteLine("You're not the only one\n");
Console.WriteLine("\nDon't ya think that you need somebody?");
Console.WriteLine("Don't ya think that you need someone?");
Console.WriteLine("Everybody needs somebody");
Console.WriteLine("You're not the only one");
Console.WriteLine("You're not the only one\n");
Console.WriteLine("\nDon't ya think that you need somebody?");
Console.WriteLine("Don't ya think that you need someone?");
Console.WriteLine("Everybody needs somebody");
